/* This file was generated by https://github.com/dested/serverless-client-builder */
/* tslint:disable */
import {ClientTransformOptions, ClientOptions, ClientSocketOptions, ControllerOptions} from './baseClient';
declare type ObjectId = string;

export class AnalyticsClient {
  static async event<TPromise = VoidResponse>(
    model: EventRequest,
    handle: {200?: (result: VoidResponse) => void; 500?: (result: string) => void; 401?: (error: string) => void}
  ): Promise<TPromise | undefined> {
    let url = ClientOptions.baseUrl + '/analytics/event?';

    return makeRequest(url, model, 'POST', handle);
  }

  static async $meta<TPromise = MetaResponse>(
    model: VoidRequest,
    handle: {200?: (result: MetaResponse) => void; 500?: (result: string) => void; 401?: (error: string) => void}
  ): Promise<TPromise | undefined> {
    let url = ClientOptions.baseUrl + '/analytics/meta?';

    return makeRequest(url, model, 'POST', handle);
  }
}

export class GameDetailsClient {
  static async getGames<TPromise = GetGamesResponse>(
    model: VoidRequest,
    handle: {200?: (result: GetGamesResponse) => void; 500?: (result: string) => void; 401?: (error: string) => void}
  ): Promise<TPromise | undefined> {
    let url = ClientOptions.baseUrl + '/game-details/?';

    return makeGetRequest(url, model, 'GET', handle);
  }

  static async getGameDetails<TPromise = GetGameDetailsResponse>(
    model: GetGameDetailsRequest,
    handle: {
      200?: (result: GetGameDetailsResponse) => void;
      500?: (result: string) => void;
      401?: (error: string) => void;
    }
  ): Promise<TPromise | undefined> {
    let url = ClientOptions.baseUrl + '/game-details/details?';

    return makeGetRequest(url, model, 'GET', handle);
  }
}

export class LobbySocketClient {
  socket?: WebSocket;
  events?: LobbySocketEvents;
  connect(events: LobbySocketEvents) {
    this.events = events;
    this.socket = new WebSocket(ClientSocketOptions.baseUrl);
    this.socket.onmessage = message => {
      if (!this.events) return;
      const response = JSON.parse(message.data);
      switch (response.event) {
        case 'playerJoin':
          this.events.onPlayerJoin && this.events.onPlayerJoin(response.data);
          break;
      }
    };
    this.socket.onclose = e => {
      this.events?.onDisconnect && this.events?.onDisconnect();
    };
    this.socket.onopen = () => {
      this.events?.onConnect && this.events?.onConnect();
    };
  }
  disconnect() {
    this.socket && this.socket.close();
  }

  playerJoin(request: PlayerJoinRequest): void {
    this.socket &&
      this.socket.send(
        JSON.stringify({
          action: 'playerJoin',
          jwt: ClientSocketOptions.getJwt(),
          data: request,
        })
      );
  }
}

export interface LobbySocketEvents {
  onPlayerJoin: (req: PlayerJoinResponse) => void;

  onDisconnect: () => void;
  onConnect: () => void;
}

export class PlayerClient {
  static async getPlayerDetails<TPromise = GetPlayerDetailsResponse>(
    model: VoidRequest,
    handle: {
      200?: (result: GetPlayerDetailsResponse) => void;
      500?: (result: string) => void;
      400: (result: {error: string}) => void;
      401?: (error: string) => void;
    }
  ): Promise<TPromise | undefined> {
    let url = ClientOptions.baseUrl + '/player/details?';

    return makeGetRequest(url, model, 'GET', handle);
  }
}

export interface EventRequest {
  eventName: string;
  metaData: string;
  time: string;
}

export interface VoidResponse {}

export interface VoidRequest {}

export interface MetaResponse {}

export interface GetGamesResponse {
  games: HttpGameDetailLight[];
}

export interface HttpGameDetailLight {
  id: string;
  logo: string;
  name: string;
  description: string;
}

export interface GetGameDetailsRequest {
  gameId: string;
}

export interface GetGameDetailsResponse {
  details: HttpGameDetail;
}

export interface HttpGameDetail {
  id: string;
  logo: string;
  name: string;
  description: string;
  author: string;
  numberOfActivePlayers: number;
}

export interface PlayerJoinRequest {
  playerId: string;
}

export interface PlayerJoinResponse {
  playerId: string;
}

export interface GetPlayerDetailsResponse {
  player: HttpPlayerModel;
}

export type HttpPlayerModel = {
  playerId: string;
  name: string;
};

async function handleResponse(responseText: string, status: number, handle: any) {
  try {
    if (handle[status]) {
      const val = responseText === '' ? null : JSON.parse(responseText);
      await handle[status](val);
      return undefined;
    } else {
      switch (status) {
        case 200: {
          return JSON.parse(responseText);
        }
        case 401: {
          ClientOptions.handleUnauthorized(responseText);
          break;
        }
        case 500: {
          const body = JSON.parse(responseText);
          ClientOptions.handleError(body.error || responseText);
          break;
        }
      }
    }
  } catch (ex) {
    if (!handle[500]) {
      ClientOptions.handleError(ex.toString());
    } else {
      await handle[500](ex.toString());
    }
  }
}
async function makeRequest(url: string, model: any, method: string, handle: any) {
  try {
    const options = {
      method,
    } as RequestInit;

    options.body = JSON.stringify(model);

    const response = await fetch(url, ClientTransformOptions(options));
    const status = response.status;
    const responseText = await response.text();
    return handleResponse(responseText, status, handle);
  } catch (ex) {
    return handleResponse(ex.toString(), 500, handle);
  }
}

async function makeGetRequest(url: string, model: any, method: string, handle: any) {
  try {
    const options = {
      method,
    } as RequestInit;
    url += Object.keys(model)
      .filter(key => !!(model as any)[key])
      .map(key => `${key}=${encodeURIComponent((model as any)[key])}`)
      .join('&');

    const response = await fetch(url, ClientTransformOptions(options));
    const status = response.status;
    const responseText = await response.text();
    return handleResponse(responseText, status, handle);
  } catch (ex) {
    return handleResponse(ex.toString(), 500, handle);
  }
}
