version: '3'

services:
  api:
    #    image: 114394156384.dkr.ecr.us-west-2.amazonaws.com/quickgame-api-harness:latest
    image: quickgame-api-harness:latest
    links:
      - mongo
      - redis
    ports:
      - "5503:5503"
    depends_on:
      - redis
      - mongo
  gameserver:
    #    image: 114394156384.dkr.ecr.us-west-2.amazonaws.com/quickgame-gameserver-harness:latest
    image: quickgame-gameserver-harness:latest
    links:
      - mongo
      - redis
    ports:
      - "33333:80"
    depends_on:
      - api
      - redis
      - mongo
  site:
    logging:
      driver: none
#    image: 114394156384.dkr.ecr.us-west-2.amazonaws.com/quickgame-site-harness:latest
    image: quickgame-site-harness:latest
    ports:
      - "44444:44444"
    depends_on:
      - api
  redis:
    logging:
      driver: none
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    logging:
      driver: none
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: quickgame-harness
      MONGO_INITDB_ROOT_USERNAME: qg
      MONGO_INITDB_ROOT_PASSWORD: qg
      DB_NAME: quickgame-harness
      DB_USER: qg
      DB_PASSWORD: qg
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
#      - data-volume:/data/db
#volumes:
#  data-volume:
